const PDFDocument = require('pdfkit');
const db = require('../config/db');
const { AppError } = require('../middleware/errorHandler');

/**
 * PDF Export Controller for Pryntis.
 *
 * Generates downloadable PDFs for templates and royalty statements
 * using PDFKit. All documents follow a consistent Pryntis brand layout.
 */

// Shared PDF helpers

const COLORS = {
  primary: '#1a1a2e',
  secondary: '#16213e',
  accent: '#0f3460',
  text: '#333333',
  muted: '#666666',
  light: '#999999',
  border: '#cccccc',
  background: '#f5f5f5',
  white: '#ffffff',
};

/**
 * Draw a standard Pryntis header on the current page.
 */
function drawHeader(doc, title, subtitle) {
  doc
    .rect(0, 0, doc.page.width, 80)
    .fill(COLORS.primary);

  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor(COLORS.white)
    .text(title, 50, 22, { width: doc.page.width - 100 });

  if (subtitle) {
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#aaaaaa')
      .text(subtitle, 50, 52, { width: doc.page.width - 100 });
  }

  doc.moveDown(3);
  doc.y = 100; // Reset cursor below header
}

/**
 * Draw a standard Pryntis footer on the current page.
 */
function drawFooter(doc) {
  const bottom = doc.page.height - 40;
  doc
    .moveTo(50, bottom - 5)
    .lineTo(doc.page.width - 50, bottom - 5)
    .strokeColor(COLORS.border)
    .stroke();

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(COLORS.light)
    .text(
      `Generated by Pryntis  |  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      50,
      bottom,
      { width: doc.page.width - 100, align: 'center' }
    );
}

/**
 * Draw a category badge inline.
 */
function drawBadge(doc, text, x, y) {
  const badgeWidth = doc.widthOfString(text) + 16;
  const badgeHeight = 18;

  doc
    .roundedRect(x, y, badgeWidth, badgeHeight, 4)
    .fill(COLORS.accent);

  doc
    .font('Helvetica-Bold')
    .fontSize(9)
    .fillColor(COLORS.white)
    .text(text.toUpperCase(), x + 8, y + 4, { width: badgeWidth - 16 });

  doc.fillColor(COLORS.text); // Reset fill
  return badgeWidth;
}

/**
 * Draw a simple table.
 * columns: [{ label, key, width, align }]
 * rows: [{ [key]: value }]
 */
function drawTable(doc, columns, rows, startX, startY) {
  const rowHeight = 22;
  let y = startY;

  // Table header
  doc
    .rect(startX, y, columns.reduce((s, c) => s + c.width, 0), rowHeight)
    .fill(COLORS.secondary);

  let x = startX;
  for (const col of columns) {
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor(COLORS.white)
      .text(col.label, x + 6, y + 6, { width: col.width - 12, align: col.align || 'left' });
    x += col.width;
  }

  y += rowHeight;

  // Table rows
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const bgColor = i % 2 === 0 ? COLORS.white : COLORS.background;
    const tableWidth = columns.reduce((s, c) => s + c.width, 0);

    doc.rect(startX, y, tableWidth, rowHeight).fill(bgColor);

    x = startX;
    for (const col of columns) {
      const value = row[col.key] != null ? String(row[col.key]) : '';
      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor(COLORS.text)
        .text(value, x + 6, y + 6, { width: col.width - 12, align: col.align || 'left' });
      x += col.width;
    }

    y += rowHeight;

    // Page break guard
    if (y > doc.page.height - 80) {
      drawFooter(doc);
      doc.addPage();
      y = 50;
    }
  }

  // Bottom border
  const tableWidth = columns.reduce((s, c) => s + c.width, 0);
  doc.moveTo(startX, y).lineTo(startX + tableWidth, y).strokeColor(COLORS.border).stroke();

  return y;
}

// Controller

const pdfController = {
  /**
   * GET /templates/:id/export.pdf
   * Export a single template as a formatted PDF document.
   */
  async exportTemplatePdf(req, res, next) {
    try {
      const { id } = req.params;

      const { rows } = await db.query(
        `SELECT t.*, u.first_name || ' ' || u.last_name AS created_by_name
         FROM templates t
         LEFT JOIN users u ON u.id = t.created_by
         WHERE t.id = $1`,
        [id]
      );

      if (!rows.length) {
        throw new AppError('Template not found', 404, 'NOT_FOUND');
      }

      const template = rows[0];

      // Sanitize title for filename
      const safeTitle = template.title
        .replace(/[^a-zA-Z0-9_\- ]/g, '')
        .replace(/\s+/g, '-')
        .substring(0, 80);

      // Create PDF
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: template.title,
          Author: 'Pryntis',
          Subject: `Template: ${template.category}`,
          Creator: 'Pryntis PDF Export',
        },
      });

      // Set response headers
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="template-${safeTitle}.pdf"`
      );

      // Pipe to response
      doc.pipe(res);

      // Header
      drawHeader(doc, template.title, `Template Export  |  ID: ${template.id}`);

      // Category badge
      drawBadge(doc, template.category, 50, doc.y);
      doc.moveDown(1.5);

      // Metadata
      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor(COLORS.muted);

      if (template.created_by_name) {
        doc.text(`Created by: ${template.created_by_name}`, 50);
      }
      if (template.created_at) {
        doc.text(
          `Created: ${new Date(template.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
          50
        );
      }
      if (template.verification_status) {
        doc.text(`Verification: ${template.verification_status}`, 50);
      }
      if (template.source_url) {
        doc.text(`Source: ${template.source_url}`, 50);
      }

      doc.moveDown(1);

      // Separator
      doc
        .moveTo(50, doc.y)
        .lineTo(doc.page.width - 50, doc.y)
        .strokeColor(COLORS.border)
        .stroke();

      doc.moveDown(1);

      // Body text — preserve line breaks
      doc
        .font('Helvetica')
        .fontSize(12)
        .fillColor(COLORS.text);

      const bodyLines = template.body.split('\n');
      for (const line of bodyLines) {
        if (doc.y > doc.page.height - 80) {
          drawFooter(doc);
          doc.addPage();
        }
        doc.text(line.trim() === '' ? ' ' : line, 50, doc.y, {
          width: doc.page.width - 100,
          lineGap: 4,
        });
      }

      // Footer
      drawFooter(doc);

      doc.end();
    } catch (err) {
      next(err);
    }
  },

  /**
   * GET /royalty/statements/:artistId.pdf?period=YYYY-Qn
   * Export a royalty statement for an artist as a PDF.
   *
   * Optional query param `period` filters by fiscal quarter, e.g. "2025-Q1".
   * Without period, all-time data is used.
   */
  async exportRoyaltyStatement(req, res, next) {
    try {
      const { artistId } = req.params;
      const { period } = req.query; // e.g. "2025-Q1"

      // Fetch artist
      const { rows: artistRows } = await db.query(
        'SELECT id, name, stage_name, email, genre, status FROM artists WHERE id = $1 AND is_deleted = false',
        [artistId]
      );

      if (!artistRows.length) {
        throw new AppError('Artist not found', 404, 'NOT_FOUND');
      }

      const artist = artistRows[0];
      const displayName = artist.stage_name || artist.name;

      // Parse period for date filtering
      let dateFilter = '';
      let dateParams = [artistId];
      let periodLabel = 'All Time';

      if (period) {
        const periodMatch = period.match(/^(\d{4})-Q([1-4])$/);
        if (!periodMatch) {
          throw new AppError(
            'Invalid period format. Use YYYY-Qn (e.g. 2025-Q1)',
            400,
            'VALIDATION_ERROR'
          );
        }

        const year = parseInt(periodMatch[1], 10);
        const quarter = parseInt(periodMatch[2], 10);
        const startMonth = (quarter - 1) * 3 + 1;
        const startDate = `${year}-${String(startMonth).padStart(2, '0')}-01`;

        // End date: first day of next quarter
        let endYear = year;
        let endMonth = startMonth + 3;
        if (endMonth > 12) {
          endMonth = 1;
          endYear = year + 1;
        }
        const endDate = `${endYear}-${String(endMonth).padStart(2, '0')}-01`;

        dateFilter = ' AND event_date >= $2 AND event_date < $3';
        dateParams = [artistId, startDate, endDate];
        periodLabel = `Q${quarter} ${year}`;
      }

      // Fetch revenue events
      const revenueQuery = `
        SELECT
          re.event_date,
          re.source,
          re.description,
          re.amount
        FROM revenue_events re
        WHERE re.artist_id = $1${dateFilter}
        ORDER BY re.event_date ASC
      `;
      const { rows: revenueRows } = await db.query(revenueQuery, dateParams);

      // Fetch recoupable expenses
      let expenseDateFilter = '';
      let expenseParams = [artistId];

      if (period) {
        expenseDateFilter = ' AND expense_date >= $2 AND expense_date < $3';
        expenseParams = dateParams;
      }

      const expenseQuery = `
        SELECT
          ex.category,
          ex.description,
          ex.amount,
          ex.expense_date
        FROM recoupable_expenses ex
        WHERE ex.artist_id = $1${expenseDateFilter}
        ORDER BY ex.expense_date ASC
      `;
      const { rows: expenseRows } = await db.query(expenseQuery, expenseParams);

      // Compute totals
      const grossRevenue = revenueRows.reduce(
        (sum, r) => sum + parseFloat(r.amount || 0),
        0
      );
      const totalExpenses = expenseRows.reduce(
        (sum, e) => sum + parseFloat(e.amount || 0),
        0
      );
      const netPayable = grossRevenue - totalExpenses;

      // Sanitize filename
      const safeName = displayName
        .replace(/[^a-zA-Z0-9_\- ]/g, '')
        .replace(/\s+/g, '-')
        .substring(0, 60);

      const periodSlug = period || 'all-time';

      // Generate PDF
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Royalty Statement - ${displayName}`,
          Author: 'Pryntis',
          Subject: `Royalty Statement for ${periodLabel}`,
          Creator: 'Pryntis PDF Export',
        },
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="royalty-statement-${safeName}-${periodSlug}.pdf"`
      );

      doc.pipe(res);

      // Header
      drawHeader(
        doc,
        `Royalty Statement - ${displayName}`,
        `Period: ${periodLabel}  |  Generated: ${new Date().toLocaleDateString('en-US')}`
      );

      // Artist info
      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor(COLORS.muted);

      doc.text(`Legal Name: ${artist.name}`, 50);
      if (artist.stage_name) doc.text(`Stage Name: ${artist.stage_name}`, 50);
      if (artist.email) doc.text(`Email: ${artist.email}`, 50);
      if (artist.genre) doc.text(`Genre: ${artist.genre}`, 50);

      doc.moveDown(1.5);

      // Revenue table
      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor(COLORS.primary)
        .text('Revenue', 50);
      doc.moveDown(0.5);

      if (revenueRows.length > 0) {
        const revColumns = [
          { label: 'Date', key: 'date', width: 100, align: 'left' },
          { label: 'Source', key: 'source', width: 160, align: 'left' },
          { label: 'Description', key: 'description', width: 160, align: 'left' },
          { label: 'Amount', key: 'amount', width: 90, align: 'right' },
        ];

        const revRows = revenueRows.map((r) => ({
          date: new Date(r.event_date).toLocaleDateString('en-US'),
          source: r.source || '-',
          description: r.description || '-',
          amount: `$${parseFloat(r.amount).toFixed(2)}`,
        }));

        const afterY = drawTable(doc, revColumns, revRows, 50, doc.y);
        doc.y = afterY + 10;
      } else {
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor(COLORS.muted)
          .text('No revenue events for this period.', 50);
        doc.moveDown(1);
      }

      doc.moveDown(1);

      // Expenses table
      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor(COLORS.primary)
        .text('Recoupable Expenses', 50);
      doc.moveDown(0.5);

      if (expenseRows.length > 0) {
        const expColumns = [
          { label: 'Date', key: 'date', width: 100, align: 'left' },
          { label: 'Category', key: 'category', width: 120, align: 'left' },
          { label: 'Description', key: 'description', width: 200, align: 'left' },
          { label: 'Amount', key: 'amount', width: 90, align: 'right' },
        ];

        const expRows = expenseRows.map((e) => ({
          date: new Date(e.expense_date).toLocaleDateString('en-US'),
          category: e.category,
          description: e.description || '-',
          amount: `$${parseFloat(e.amount).toFixed(2)}`,
        }));

        const afterY = drawTable(doc, expColumns, expRows, 50, doc.y);
        doc.y = afterY + 10;
      } else {
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor(COLORS.muted)
          .text('No recoupable expenses for this period.', 50);
        doc.moveDown(1);
      }

      doc.moveDown(1.5);

      // Summary
      // Page break guard for summary block
      if (doc.y > doc.page.height - 160) {
        drawFooter(doc);
        doc.addPage();
      }

      doc
        .moveTo(50, doc.y)
        .lineTo(doc.page.width - 50, doc.y)
        .strokeColor(COLORS.border)
        .stroke();

      doc.moveDown(0.8);

      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor(COLORS.primary)
        .text('Summary', 50);
      doc.moveDown(0.5);

      const summaryX = 50;
      const valueX = 300;

      doc.font('Helvetica').fontSize(12).fillColor(COLORS.text);

      doc.text('Gross Revenue:', summaryX, doc.y);
      doc.text(`$${grossRevenue.toFixed(2)}`, valueX, doc.y - 14.4, { align: 'left' });
      doc.moveDown(0.5);

      doc.text('Total Recoupable Expenses:', summaryX, doc.y);
      doc.text(`($${totalExpenses.toFixed(2)})`, valueX, doc.y - 14.4, { align: 'left' });
      doc.moveDown(0.5);

      // Net line separator
      doc
        .moveTo(summaryX, doc.y)
        .lineTo(420, doc.y)
        .strokeColor(COLORS.border)
        .stroke();
      doc.moveDown(0.5);

      doc
        .font('Helvetica-Bold')
        .fontSize(13)
        .fillColor(netPayable >= 0 ? '#006600' : '#cc0000');

      doc.text('Net Payable:', summaryX, doc.y);
      doc.text(`$${netPayable.toFixed(2)}`, valueX, doc.y - 15.6, { align: 'left' });

      doc.fillColor(COLORS.text); // Reset

      // Footer
      drawFooter(doc);

      doc.end();
    } catch (err) {
      next(err);
    }
  },
};

module.exports = pdfController;
